### ISSUE TITLE
Add Support "Semi-persistent Storage" with K8s persistent volumes

### ISSUE THREAD

**Issue by jpthurman** [UffizziCloud/uffizzi_core#10]
Use case-
User creates a preview environment and adds data to their database for the Preview Environment.  We want that data to be written to a persistent volume and for it to persist for the life of the preview environment.  

If defined in compose the volume will be created with a new preview deployment and then removed when the preview environment is closed out.  

This would prevent any "golden data" or data added during the preview existence from being wiped out every time there's a new image pushed.

**Comment by gadkins** [comment]
Closing this issue as it is being implemented here: https://github.com/UffizziCloud/uffizzi_app/issues/126
